package com.ranieriiuri.eclesial_arrecadacoes.domain.enums;

public enum CategoriaPeca {
    ROUPA_MASCULINA_ADULTA,
    ROUPA_FEMININA_ADULTA,
    ROUPA_MASCULINA_INFANTIL,
    ROUPA_FEMININA_INFANTIL,
    CALCADO_MASCULINO_ADULTO,
    CALCADO_FEMININO_ADULTO,
    CALCADO_MASCULINO_INFANTIL,
    CALCADO_FEMININO_INFANTIL,
    ACESSORIO_MASCULINO_ADULTO,
    ACESSORIO_FEMININO_ADULTO,
    ACESSORIO_MASCULINO_INFANTIL,
    ACESSORIO_FEMININO_INFANTIL
}
